import type { GeneratedSVModel, PrimitivePort, PrimitiveInstance } from '../../types/primitive-types';
import { primitiveLibrary } from '../../primitives/primitive-registry';

/**
 * SV Model Generator
 *
 * Renders a GeneratedSVModel (structural mapped CIR) into
 * SystemVerilog code compatible with VCS, Xcelium, and Questa.
 */
export class SVModelGenerator {
  generate(model: GeneratedSVModel): string {
    const parts: string[] = [];

    parts.push(this.generateHeader(model));
    parts.push(this.generatePorts(model));
    parts.push(this.generateParams(model));
    parts.push(this.generateInternals(model));
    parts.push('');

    for (const inst of model.instances) {
      parts.push(this.renderInstance(inst));
    }

    parts.push(this.generateFooter(model));
    return parts.join('\n');
  }

  private generateHeader(model: GeneratedSVModel): string {
    return `// Generated by GenRTL Analog Model Generator
// Source: ${model.metadata.sourceCircuit || 'unknown'}
// Generated: ${model.metadata.generatedAt.toISOString()}
// Primitives: ${model.metadata.primitiveCount}
// Warnings: ${model.metadata.warnings.length}

module ${model.name} (`;
  }

  private generatePorts(model: GeneratedSVModel): string {
    const portLines = model.ports.map(p => {
      const direction = p.direction === 'inout' ? 'inout' : p.direction === 'output' ? 'output' : 'input';
      const typeStr = p.width && p.width > 1
        ? `${direction} ${p.svType} [${p.width-1}:0] ${p.name}`
        : `${direction} ${p.svType} ${p.name}`;
      return `  ${typeStr}`;
    });
    return portLines.join(',\n');
  }

  private generateParams(model: GeneratedSVModel): string {
    if (model.params.length === 0) return ');\n';
    const lines = model.params.map(p => {
      const defaultStr = typeof p.defaultValue === 'string' ? `"${p.defaultValue}"` : String(p.defaultValue);
      return `  parameter ${p.svType} ${p.name} = ${defaultStr}`;
    });
    return `);\n` + lines.join(',\n');
  }

  private generateInternals(model: GeneratedSVModel): string {
    const lines: string[] = [];
    for (const net of model.internalNets) {
      if (net.type === 'real') {
        lines.push(`  real ${net.name};`);
      } else if (net.type === 'logic' && net.width) {
        lines.push(`  logic [${net.width-1}:0] ${net.name};`);
      } else if (net.type === 'wire') {
        lines.push(`  wire ${net.name};`);
      }
    }
    if (lines.length > 0) lines.push('');
    return lines.join('\n');
  }

  private renderInstance(inst: PrimitiveInstance): string {
    const def = primitiveLibrary.get(inst.primitiveName);
    if (!def) return `  // Unknown primitive: ${inst.primitiveName}\n`;

    const hasParams = Object.keys(inst.paramOverrides).length > 0;
    const lines: string[] = [];

    lines.push(`  ${def.name} #(`);
    const paramStrs = Object.entries(inst.paramOverrides).map(([k, v]) => `    .${k}(${v})`);
    lines.push(paramStrs.join(',\n'));
    if (!hasParams) lines[lines.length-1] = lines[lines.length-1].replace(/#\(/, '');
    lines.push(`${hasParams ? '  ' : ''}) ${inst.instanceName} (`);

    const portStrs = Object.entries(inst.portConnections).map(([port, net]) => `    .${port}(${net})`);
    lines.push(portStrs.join(',\n'));
    lines.push('  );');
    lines.push('');

    return lines.join('\n');
  }

  private generateFooter(model: GeneratedSVModel): string {
    return `endmodule

// ============================================================
// Module: ${model.name}
// Instance count: ${model.metadata.totalInstances}
// ============================================================
`;
  }
}
